# Software Name : Ontologie2Graph
# SPDX-FileCopyrightText: Copyright (c) Orange SA
# SPDX-License-Identifier: BSD-4-Clause
#
# This software is distributed under the BSD 4-Clause "Original" or "Old" License,
# see the "LICENSE" file for more details or <license-url>

''' Knowledge Graph Visualization and KPI Analysis Tool

This script provides comprehensive visualization and analysis capabilities for TTL (Turtle) 
knowledge graphs. It can process individual files or entire directories, generating 
interactive HTML visualizations and computing key performance indicators (KPIs) for 
graph structure analysis.

The script supports two visualization modes:
- Basic Mode: Simple graph visualization with standard node and edge rendering
- Advanced Mode: Enhanced visualization with node type categorization and advanced styling

Main Features:
- Interactive HTML graph visualizations using web-based rendering
- KPI computation including node count, density, and connectivity metrics
- Batch processing of multiple TTL files in a directory
- Ontology-aware node type classification for advanced visualizations
- Cumulative statistics across multiple graphs
- Comprehensive logging of analysis results

Visualization Outputs:
- HTML files with interactive graph representations
- KPI logs with detailed graph metrics
- Node type analysis (in advanced mode)
- Cumulative statistics for batch processing

Usage:
python display_graphs.py --path <file_or_directory> --ontology <ontology_file> \
    --mode <basic|advanced>

Arguments:
    --path: Path to a single TTL file or directory containing TTL files
    --ontology: Path to the ontology TTL file for node type classification
    --mode: Visualization mode ('basic' or 'advanced')

Modes:
    basic: Standard graph visualization with basic node and edge styling
    advanced: Enhanced visualization with node type categorization, color coding,
             and detailed type-specific analysis

Output Structure:
    log_html/
    ├── graph_visualizations/     # HTML visualization files
    ├── graph_kpi.log            # KPI analysis results
    └── [timestamp]/             # Timestamped output directories

Dependencies:
    - pathlib: Cross-platform path handling
    - utils.utils_display: Graph visualization utilities
    - utils_common.utils: Shared utilities for logging and argument parsing
    - External web rendering libraries for HTML graph generation

KPI Metrics:
    - Node count and distribution
    - Graph density and connectivity
    - Node type frequencies (advanced mode)
    - Cumulative statistics for batch processing
    - Edge relationship patterns

Example:
    # Visualize single file in basic mode
    python display_graphs.py --path /path/to/graph.ttl --ontology ontology.ttl --mode basic
    
    # Batch process directory in advanced mode
    python display_graphs.py --path /path/to/graphs/ --ontology ontology.ttl --mode advanced

Integration:
    This tool integrates with the Ontologie2Graph ecosystem for:
    - Analyzing synthetic graphs generated by LLMs
    - Quality assessment of knowledge graph collections
    - Visual inspection of merged graph structures
    - Performance monitoring of graph generation processes'''

import logging
from pathlib import Path
from utils import utils_display as utils
from utils import visu_graph as visu
from utils_common import utils as utils_common

### set argument parser ###
args = utils_common.setup_argument_parser([("path", "path where files are stored")\
                                ,("ontology", "ontology file "),("mode", "display mode")])

if args.mode not in ["basic", "advanced"]:
    raise ValueError("Mode must be either 'basic' or 'advanced'")

### initialize cumulative variables ###
CUMUL_NODES=0
CUMUL_DENSITY=0

### create new log_html_folder and clean old logs ###
log_html_folder=utils.create_new_log_html_folder(args.path)
log_file=Path(f'{log_html_folder}/graph_kpi.log')

### set logger ###
logger = utils_common.setup_logger(log_file,'graph_kpi',logging.INFO)

### display graphs and compute kpis ###
if Path(args.path).is_file():
    file_name=Path(args.path).name
    absolute_file_name=Path(f'{Path(args.path).parent.resolve()}/{file_name}')

    Digraph, node_type_lists = utils.prepare_graph_to_display(args.path,log_html_folder,\
            args.ontology,args.mode)
    utils.log_kpis(file_name, Digraph, CUMUL_NODES, CUMUL_DENSITY, args.mode, node_type_lists)

    if args.mode=='basic':
        visu.visu_graph_basic(Digraph, absolute_file_name, log_html_folder)
    elif args.mode=='advanced':
        visu.visu_graph_advanced(Digraph,absolute_file_name,log_html_folder,node_type_lists)

else :
    all_files = [str(f.resolve()) for f in Path(args.path).iterdir() if f.is_file()]

    for file in all_files :
        Digraph, node_type_lists = utils.prepare_graph_to_display(file,log_html_folder,\
            args.ontology,args.mode)
        CUMUL_NODES,CUMUL_DENSITY = utils.log_kpis(file,Digraph,CUMUL_NODES,CUMUL_DENSITY,\
                                                        args.mode,node_type_lists)

        if args.mode=='basic':
            visu.visu_graph_basic(Digraph, file, log_html_folder)
        elif args.mode=='advanced':
            visu.visu_graph_advanced(Digraph, file, log_html_folder,node_type_lists)
