#!/usr/bin/env python3
# Software Name : Ontologie2Graph
# SPDX-FileCopyrightText: Copyright (c) Orange SA
# SPDX-License-Identifier: BSD-4-Clause
#
# This software is distributed under the BSD 4-Clause "Original" or "Old" License,
# see the "LICENSE" file for more details or <license-url>

''' Find Duplicate Nodes Across Multiple TTL Graph Files

This script analyzes a collection of TTL (Turtle) RDF files to identify nodes that appear in 
multiple graphs, helping to understand node overlap and potential merge opportunities in knowledge
graph collections.

The script performs the following operations:
1. Scans a directory for all TTL files
2. Parses each TTL file using RDFLib to extract RDF triples
3. Filters out metadata predicates (labels, types, descriptions, etc.)
4. Excludes datatype properties defined in the specified ontology
5. Extracts nodes from each graph's meaningful relationships
6. Counts node occurrences across all files
7. Identifies and reports duplicate nodes (appearing in multiple files)

This tool is particularly useful for:
- Analyzing synthetic knowledge graphs generated by LLMs
- Identifying common entities across graph collections
- Preparing data for graph merging operations
- Understanding node distribution patterns

Usage:
    python find_duplicates_nodes.py <path_to_ttl_directory> <ontology_file>

Arguments:
    path_to_ttl_directory: Path to directory containing TTL files to analyze
    ontology_file: Path to the ontology TTL file (used to identify datatype properties)

Output:
    Prints a list of duplicate nodes found across multiple TTL files.

Filtered Predicates:
    - label: Node labels and naming properties
    - type: RDF type declarations  
    - inScheme: SKOS concept scheme relationships
    - description: Descriptive text properties
    - comment: Comment annotations
    - All datatype properties defined in the specified ontology

Dependencies:
    - rdflib: For RDF/Turtle file parsing
    - networkx: For graph structure creation and node extraction
    - collections.Counter: For counting node occurrences
    - pathlib: For cross-platform path handling
    - utils_common.utils: For ontology object retrieval

Example:
    python find_duplicates_nodes.py /path/to/ttl/files/ /path/to/ontology.ttl
    # Output: DUPLICATES ['Person_1', 'Organization_2', 'Location_5'], '''

import sys
from pathlib import Path
from collections import Counter
import networkx as nx
import rdflib
from utils_common.utils import retreive_onto_object

arg = sys.argv[1:]
PATH= arg[0]
ONTOLOGY = arg[1]

### List all the ttl graph files in PATH except folder ###
all_files = [f.name for f in Path(PATH).iterdir() if f.is_file()]

DataTypeProperties=retreive_onto_object(ONTOLOGY,'DatatypeProperty')

### rebuild complete file path (folder/file) ###
for i, file in enumerate(all_files):
    all_files[i]= PATH + file

j=0
all_nodes=[]
nodes=[]

### populate graphqs from all ttl files ###
for file in all_files :

    g = rdflib.Graph()
    g.parse(file, format="turtle")

    nx_graph = nx.DiGraph()

    for subj, pred, obj in g:
        last_part_pred=Path(str(pred)).name

        if ('label' in last_part_pred) or ('type' in last_part_pred) or\
           ('inScheme' in last_part_pred) or ('description' in last_part_pred) or\
           ('comment' in last_part_pred) or last_part_pred in DataTypeProperties:
            pass

        else :
            last_part_subj=Path(str(subj)).name
            last_part_obj=Path(str(obj)).name
            nx_graph.add_edge(str(last_part_subj),str(last_part_obj),label=str(last_part_pred))

    nodes=list(nx_graph.nodes)
    all_nodes.append(nodes)

### transform list of list into a simple list ###
all_nodes_list = [item for sublist in all_nodes for item in sublist]

counts=Counter(all_nodes_list)
duplicates=[item for item, count in counts.items() if count > 1]
print(f'DUPLICATES {duplicates},\n')

all_nodes_list_unique = list(set(all_nodes_list))
