'''This function merge several knowledge Graphs in an only one. You have to pass as a parameter the
 folder where are stored the Graphs generated by LLM and the number of node's occurrence you want 
 to keep in all these files'''

import argparse
import os
from pathlib import Path
#from merge_ttl_files.utils.utils_merge import rename_duplicates_nodes,remove_duplicate_prefix
#from merge_ttl_files.utils.utils_merge import find_duplicates_nodes,check_ttl

#from utils.utils_merge import rename_duplicates_nodes,remove_duplicate_prefix
#from utils.utils_merge import find_duplicates_nodes,check_ttl 

#from utils_merge import rename_duplicates_nodes,remove_duplicate_prefix
#from utils_merge import find_duplicates_nodes,check_ttl

from utils.utils_merge import rename_duplicates_nodes,remove_duplicate_prefix
from utils.utils_merge import find_duplicates_nodes,check_ttl

#def merge_ttl(path_result,path_merged,ontology,nbr_occ_max):

#    '''function to merge ttl files'''
parser = argparse.ArgumentParser()
parser.add_argument("path_result")
parser.add_argument("path_merged")
parser.add_argument("ontology")
parser.add_argument("nbr_occ_max")

args = parser.parse_args()

path_result=args.path_result
path_merged=args.path_merged
ontology=args.ontology
nbr_occ_max=args.nbr_occ_max

    #path_result=f'{PATH}/merged_graph/'
    #path_result=f'{path}/merged_graph'
    #merged_file=f'{path_merged}/merged_graph_{remain_occ}.ttl'
    #merged_ttl_temp=f'{path_result}/merged_ttl_temp.ttl'
    #merged_ttl_final=f'{path_result}/merged_ttl_final.ttl'

bad_path_result=f'{path_result}/bad_Turtle_Syntax'
bad_merged_file=f'{bad_path_result}/merged_graph_BAD.ttl'
    #output_file_temp=f'{path_result}/temp.ttl'

    #Merge the ttl file
    #all_graphs = [f.name for f in Path(path_result).iterdir() if f.is_file()]
os.makedirs(f'{path_result}',exist_ok=True)

    #with open(merged_file, 'w', encoding='utf-8') as m_file:
    #    for filename in all_graphs:
            # Open each input file in read mode
    #        with open(f'{path_result}/{filename}', 'r', encoding='utf-8') as infile:
                #Read the content and write it to the output file
    #            content = infile.read()
    #            m_file.write(content)
    #            m_file.write('\n')  # Adds a newline between
    #    print('m_file',m_file)

    #manage duplicate nodes in ttl files
duplicates=find_duplicates_nodes(path_result,ontology)
rename_duplicates_nodes(path_result,path_merged,duplicates,nbr_occ_max)

    #Merge the ttl file
    #all_graphs = [f.name for f in Path(path).iterdir() if f.is_file()]
    #os.makedirs(f'{path_result}',exist_ok=True)

    #with open(output_file_temp, 'w', encoding='utf-8') as outfile:
    #    for filename in all_graphs:
            # Open each input file in read mode
    #        with open(f'{path}/{filename}', 'r', encoding='utf-8') as infile:
                # Read the content and write it to the output file
    #            content = infile.read()
    #            outfile.write(content)
    #            outfile.write('\n')  # Adds a newline between files

    # manage prefix in merged file

all_merged_files = [f.name for f in Path(path_merged).iterdir() if f.is_file()]

for merged_file in all_merged_files:        
    remove_duplicate_prefix(Path(path_merged)/merged_file)
    check_ttl(Path(path_merged)/merged_file,bad_merged_file,bad_path_result,1)

    # restore ttl file
    #for file in glob.glob(os.path.join(path, '*.ttl')):
    #    os.remove(file)

    #src_folder=Path(f'{path}/raw_file')
    #dst_folder=Path(f'{path}/')

    #for file in src_folder.iterdir():
    #    if file.is_file():
    #        shutil.copy2(file, dst_folder / file.name)

    # validate ttl syntax
    #check_ttl(merged_file,bad_merged_file,bad_path_result,1)

    #return path_result
