'''This function merge several knowledge Graphs in an only one. You have to pass as a parameter the
 folders where are stored the Graphs generated by LLM and the ontology '''

from ast import arguments
from pathlib import Path
from utils.utils_merge import merge_ttl_graphs, manage_prefix, check_ttl, find_duplicates_nodes,\
    max_node_occ_value
from utils_common.utils import setup_argument_parser, remove_file_in_folder, setup_logger,\
    build_folder_paths_and_files

#sys.path.append('/home/pdooze/DIGITAL_TWIN/gengraphllm')

### Set up argument parser ###
arguments= [("path_file", "Graphs file path"), ("ontology", "Ontology file path")]
args = setup_argument_parser("parser", arguments)
path_file=args.path_file
ontology=args.ontology

### Set up file paths ###
_, BAD_PATH_RESULT, _, _, _, _,LOG_FILE, PATH_MERGED = build_folder_paths_and_files('None','merge')
remove_file_in_folder(Path(LOG_FILE).parent)
remove_file_in_folder(Path(PATH_MERGED))

#PATH_MERGED=f'{path_file}/merged'
#os.makedirs(f'{PATH_MERGED}',exist_ok=True)
#remove_file_in_folder(Path(PATH_MERGED))
#BAD_PATH_RESULT=f'{path_file}/bad_Turtle_Syntax'
#LOG_FILE=f'{Path(PATH_MERGED)}/Merged_file.log'

### Set up logger ###
logger= setup_logger(LOG_FILE,'merge_log')

### Find duplicates nodes and max occurrence value ###
duplicates = find_duplicates_nodes(path_file,ontology)
occ_max = max_node_occ_value(path_file,ontology)

### Merge ttl files ###
merge_ttl_graphs(path_file,PATH_MERGED,duplicates,occ_max[0])

manage_prefix(PATH_MERGED)

check_ttl(PATH_MERGED,BAD_PATH_RESULT,1)
