'''This function merge several knowledge Graphs in an only one. You have to pass as a parameter the
 folders where are stored the Graphs generated by LLM and the ontology '''

import argparse
import os

from utils.utils_merge import merge_ttl_graphs,manage_prefix
from utils.utils_merge import find_duplicates_nodes,check_ttl,max_node_occ_value

parser = argparse.ArgumentParser()
parser.add_argument("path_result")
parser.add_argument("ontology")
args = parser.parse_args()

path_result=args.path_result
ontology=args.ontology

PATH_MERGED=f'{path_result}/merged'
BAD_PATH_RESULT=f'{path_result}/bad_Turtle_Syntax'
duplicates = find_duplicates_nodes(path_result,ontology)
occ_max = max_node_occ_value(path_result,ontology)
print(occ_max)

os.makedirs(f'{path_result}',exist_ok=True)

merge_ttl_graphs(path_result,PATH_MERGED,duplicates,occ_max[0])

manage_prefix(PATH_MERGED)

check_ttl(PATH_MERGED,BAD_PATH_RESULT,1)
